pub mod wma;
pub mod vwap;
pub mod geometry;
pub mod atr;
pub mod candle_aggregator;
pub mod price_action;
pub mod support_resistance;
pub mod fibonacci;
pub mod smc;
pub mod volume_profile;

pub use wma::calculate_wma;
pub use vwap::VwapCalculator;
pub use geometry::{TrendGeometry, TrendDNA, GeometryEngine};
pub use atr::AtrCalculator;
pub use candle_aggregator::CandleAggregator;
pub use price_action::{detect_patterns, Pattern};
pub use support_resistance::{calculate_sr_zones, SrZone};
pub use fibonacci::{calculate_fib_levels, calculate_confluence_score, FibLevels};
pub use smc::{detect_smc_patterns, SmcSignals};
pub use volume_profile::{calculate_volume_profile, VolumeProfile};
